### ISSUE TITLE
Deleting a character in `TextFileTab`

### ISSUE THREAD

**Issue by randombyte-developer** [simon816/TabbedChat#2]
When using the `TextFileTab` there seems to be no way of deleting a character.

My suggestion:
- Shift + Click does the same as now but only when clicking on the beginning of a line
- Shift + Click on a character deletes all characters between the caret and the clicked char

**Comment by simon816** [comment]
That's a good suggestion.
I'm not sure how practical or usable the text editor really is so I haven't developed it further than the initial idea.
If I see a demand or a good use case for an in game text editor I'll rewrite it (It's kind of badly written right now)
Thanks for the suggestion though!
