### ISSUE TITLE
Just a couple questions

### ISSUE THREAD

**Issue by EmanYm** [simon816/TabbedChat#4]
Now that I have ChatUI installed on the server, configured and working, how would I go about creating a "tab" that prints when a command is used?
As an example, I want to know when someone uses `/give <player> <item>` or `/kick <player> [reason]`

Also, if someone with the node `chatui.admin.group.create` creates a group, will any groups they create be global (for everyone with chatui enabled) or only for themself?
(I am going to assume it's "global"

Somewhat related to the last question.
Would it be possible to have custom group nodes?  Something like `chatui.admin.group.create.<customGroup>` and then a new node `chatui.admin.group.join.<customGroup>`

**Comment by simon816** [comment]
> Now that I have ChatUI installed on the server, configured and working, how would I go about creating a "tab" that prints when a command is used?

Are you asking about developing an extension to Chat UI, or coming from a server admin's perspective? It's possible to create a plugin that adds this feature but it's not built-in.

> Also, if someone with the node `chatui.admin.group.create` creates a group, will any groups they create be global (for everyone with chatui enabled) or only for themself?

All groups are global and are accessible to all players with Chat UI enabled.

> Would it be possible to have custom group nodes?

While I agree this would be a good idea, I created the chat group feature more as a demonstrational feature (as stated on the [wiki](https://github.com/simon816/ChatUI/wiki/features#chat-groups)). Ideally, I'm interested in creating bridges between Chat UI and other plugins. If you find a plugin that offers chat group functionality I can integrate it into Chat UI, or suggest to the the plugin developer they could integrate with Chat UI.

**Comment by EmanYm** [comment]
>Are you asking about developing an extension to Chat UI, or coming from a server admin's perspective? It's possible to create a plugin that adds this feature but it's not built-in.

I was curious if I could set up a tab that printed command usage out of the box.  Judging from your response I'm going to assume it's not possible.

>All groups are global and are accessible to all players with Chat UI enabled.

That clears up who I give those permission nodes to.  Thank you

I'm interested to see what direction this goes in.  If I was still involved with modding myself - or if I decided to get back in to it - I would try to do something for this.  Unfortunately I haven't been a Minecraft Modder since roughly MC1.2/1.3
